/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param usedCells 
 * @param usedBits 
 * @param usedPublicCells 
 * @param lastPaid time of the last payment
 * @param duePayment 
 */
data class AccountStorageInfo (

    val usedCells: kotlin.Long,
    val usedBits: kotlin.Long,
    val usedPublicCells: kotlin.Long,
    /* time of the last payment */
    val lastPaid: kotlin.Long,
    val duePayment: kotlin.Long
) {
}