/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param name Display name. Data collected from different sources like moderation lists, dns, collections names and over.
 * @param isScam Is this account was marked as part of scammers activity
 * @param icon 
 * @param isWallet 
 */
data class AccountAddress (

    val address: kotlin.String,
    /* Display name. Data collected from different sources like moderation lists, dns, collections names and over. */
    val name: kotlin.String? = null,
    /* Is this account was marked as part of scammers activity */
    val isScam: kotlin.Boolean,
    val icon: kotlin.String? = null,
    val isWallet: kotlin.Boolean
) {
}