/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param address 
 * @param balance 
 * @param currenciesBalance {'USD': 1, 'IDR': 1000}
 * @param lastActivity unix timestamp
 * @param status 
 * @param interfaces 
 * @param name 
 * @param isScam 
 * @param icon 
 * @param memoRequired 
 * @param getMethods 
 * @param isSuspended 
 * @param isWallet 
 */
data class Account (

    val address: kotlin.String,
    val balance: kotlin.Long,
    /* {'USD': 1, 'IDR': 1000} */
    val currenciesBalance: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    /* unix timestamp */
    val lastActivity: kotlin.Long,
    val status: AccountStatus,
    val interfaces: kotlin.Array<kotlin.String>? = null,
    val name: kotlin.String? = null,
    val isScam: kotlin.Boolean? = null,
    val icon: kotlin.String? = null,
    val memoRequired: kotlin.Boolean? = null,
    val getMethods: kotlin.Array<kotlin.String>,
    val isSuspended: kotlin.Boolean? = null,
    val isWallet: kotlin.Boolean
) {
}