/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param pool 
 * @param amount 
 * @param pendingDeposit 
 * @param pendingWithdraw 
 * @param readyWithdraw 
 */
data class AccountStakingInfo (

    val pool: kotlin.String,
    val amount: kotlin.Long,
    val pendingDeposit: kotlin.Long,
    val pendingWithdraw: kotlin.Long,
    val readyWithdraw: kotlin.Long
) {
}