/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * An event is built on top of a trace which is a series of transactions caused by one inbound message. TonAPI looks for known patterns inside the trace and splits the trace into actions, where a single action represents a meaningful high-level operation like a Jetton Transfer or an NFT Purchase. Actions are expected to be shown to users. It is advised not to build any logic on top of actions because actions can be changed at any time.
 * @param eventId 
 * @param account 
 * @param timestamp 
 * @param actions 
 * @param isScam scam
 * @param lt 
 * @param inProgress Event is not finished yet. Transactions still happening
 * @param extra TODO
 */
data class AccountEvent (

    val eventId: kotlin.String,
    val account: AccountAddress,
    val timestamp: kotlin.Long,
    val actions: kotlin.Array<Action>,
    /* scam */
    val isScam: kotlin.Boolean,
    val lt: kotlin.Long,
    /* Event is not finished yet. Transactions still happening */
    val inProgress: kotlin.Boolean,
    /* TODO */
    val extra: kotlin.Long
) {
}