/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * shortly describes what this action is about.
 * @param name 
 * @param description 
 * @param actionImage a link to an image for this particular action.
 * @param value 
 * @param valueImage a link to an image that depicts this action's asset.
 * @param accounts 
 */
data class ActionSimplePreview (

    val name: kotlin.String,
    val description: kotlin.String,
    /* a link to an image for this particular action. */
    val actionImage: kotlin.String? = null,
    val value: kotlin.String? = null,
    /* a link to an image that depicts this action's asset. */
    val valueImage: kotlin.String? = null,
    val accounts: kotlin.Array<AccountAddress>
) {
}