/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param success 
 * @param resultCode 
 * @param totalActions 
 * @param skippedActions 
 * @param fwdFees 
 * @param totalFees 
 * @param resultCodeDescription 
 */
data class ActionPhase (

    val success: kotlin.Boolean,
    val resultCode: kotlin.Int,
    val totalActions: kotlin.Int,
    val skippedActions: kotlin.Int,
    val fwdFees: kotlin.Long,
    val totalFees: kotlin.Long,
    val resultCodeDescription: kotlin.String? = null
) {
}