/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param auctionType 
 * @param amount 
 * @param nft 
 * @param bidder 
 * @param auction 
 */
data class AuctionBidAction (

    val auctionType: AuctionType,
    val amount: Price,
    val nft: NftItem? = null,
    val bidder: AccountAddress,
    val auction: AccountAddress
) {
    /**
    * 
    * Values: DNSPERIODTON,DNSPERIODTG,NUMBERPERIODTG,GETGEMS
    */
    enum class AuctionType(val value: kotlin.String){
        DNSPERIODTON("DNS.ton"),
        DNSPERIODTG("DNS.tg"),
        NUMBERPERIODTG("NUMBER.tg"),
        GETGEMS("getgems");
    }
}