/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param domain 
 * @param owner 
 * @param price 
 * @param bids 
 * @param date 
 */
data class Auction (

    val domain: kotlin.String,
    val owner: kotlin.String,
    val price: kotlin.Long,
    val bids: kotlin.Long,
    val date: kotlin.Long
) {
}