/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Minting fees of new currencies.
 * @param mintNewPrice 
 * @param mintAddPrice 
 */
data class BlockchainConfig6 (

    val mintNewPrice: kotlin.Long,
    val mintAddPrice: kotlin.Long
) {
}