/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param code 
 * @param codeHash 
 * @param methods 
 * @param compiler 
 */
data class BlockchainAccountInspect (

    val code: kotlin.String,
    val codeHash: kotlin.String,
    val methods: kotlin.Array<BlockchainAccountInspectMethods>,
    val compiler: Compiler? = null
) {
    /**
    * 
    * Values: FUNC
    */
    enum class Compiler(val value: kotlin.String){
        FUNC("func");
    }
}