/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * List of critical TON parameters, the change of which significantly affects the network, so more voting rounds are held.
 * @param criticalParams 
 */
data class BlockchainConfig10 (

    val criticalParams: kotlin.Array<kotlin.Int>
) {
}