/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountStatus
import io.swagger.client.models.AccountStorageInfo
import io.swagger.client.models.BlockchainRawAccountLibraries

/**
 * 
 * @param address 
 * @param balance 
 * @param extraBalance 
 * @param code 
 * @param &#x60;data&#x60; 
 * @param lastTransactionLt 
 * @param lastTransactionHash 
 * @param frozenHash 
 * @param status 
 * @param storage 
 * @param libraries 
 */
data class BlockchainRawAccount (

    val address: kotlin.String,
    val balance: kotlin.Long,
    val extraBalance: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val code: kotlin.String? = null,
    val `data`: kotlin.String? = null,
    val lastTransactionLt: kotlin.Long,
    val lastTransactionHash: kotlin.String? = null,
    val frozenHash: kotlin.String? = null,
    val status: AccountStatus,
    val storage: AccountStorageInfo,
    val libraries: kotlin.Array<BlockchainRawAccountLibraries>? = null
) {
}