/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param utimeSince 
 * @param bitPricePs 
 * @param cellPricePs 
 * @param mcBitPricePs 
 * @param mcCellPricePs 
 */
data class BlockchainConfig18StoragePrices (

    val utimeSince: kotlin.Long,
    val bitPricePs: kotlin.Long,
    val cellPricePs: kotlin.Long,
    val mcBitPricePs: kotlin.Long,
    val mcCellPricePs: kotlin.Long
) {
}