/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * The configuration for the consensus protocol above catchain.
 * @param flags 
 * @param newCatchainIds 
 * @param roundCandidates 
 * @param nextCandidateDelayMs 
 * @param consensusTimeoutMs 
 * @param fastAttempts 
 * @param attemptDuration 
 * @param catchainMaxDeps 
 * @param maxBlockBytes 
 * @param maxCollatedBytes 
 * @param protoVersion 
 * @param catchainMaxBlocksCoeff 
 */
data class BlockchainConfig29 (

    val flags: kotlin.Int? = null,
    val newCatchainIds: kotlin.Boolean? = null,
    val roundCandidates: kotlin.Long,
    val nextCandidateDelayMs: kotlin.Long,
    val consensusTimeoutMs: kotlin.Long,
    val fastAttempts: kotlin.Long,
    val attemptDuration: kotlin.Long,
    val catchainMaxDeps: kotlin.Long,
    val maxBlockBytes: kotlin.Long,
    val maxCollatedBytes: kotlin.Long,
    val protoVersion: kotlin.Long? = null,
    val catchainMaxBlocksCoeff: kotlin.Long? = null
) {
}