/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param txQuantity 
 * @param valueFlow 
 * @param workchainId 
 * @param shard 
 * @param seqno 
 * @param rootHash 
 * @param fileHash 
 * @param globalId 
 * @param version 
 * @param afterMerge 
 * @param beforeSplit 
 * @param afterSplit 
 * @param wantSplit 
 * @param wantMerge 
 * @param keyBlock 
 * @param genUtime 
 * @param startLt 
 * @param endLt 
 * @param vertSeqno 
 * @param genCatchainSeqno 
 * @param minRefMcSeqno 
 * @param prevKeyBlockSeqno 
 * @param genSoftwareVersion 
 * @param genSoftwareCapabilities 
 * @param masterRef 
 * @param prevRefs 
 * @param inMsgDescrLength 
 * @param outMsgDescrLength 
 * @param randSeed 
 * @param createdBy 
 */
data class BlockchainBlock (

    val txQuantity: kotlin.Int,
    val valueFlow: BlockValueFlow,
    val workchainId: kotlin.Int,
    val shard: kotlin.String,
    val seqno: kotlin.Int,
    val rootHash: kotlin.String,
    val fileHash: kotlin.String,
    val globalId: kotlin.Int,
    val version: kotlin.Int,
    val afterMerge: kotlin.Boolean,
    val beforeSplit: kotlin.Boolean,
    val afterSplit: kotlin.Boolean,
    val wantSplit: kotlin.Boolean,
    val wantMerge: kotlin.Boolean,
    val keyBlock: kotlin.Boolean,
    val genUtime: kotlin.Long,
    val startLt: kotlin.Long,
    val endLt: kotlin.Long,
    val vertSeqno: kotlin.Int,
    val genCatchainSeqno: kotlin.Int,
    val minRefMcSeqno: kotlin.Int,
    val prevKeyBlockSeqno: kotlin.Int,
    val genSoftwareVersion: kotlin.Int? = null,
    val genSoftwareCapabilities: kotlin.Long? = null,
    val masterRef: kotlin.String? = null,
    val prevRefs: kotlin.Array<kotlin.String>,
    val inMsgDescrLength: kotlin.Long,
    val outMsgDescrLength: kotlin.Long,
    val randSeed: kotlin.String,
    val createdBy: kotlin.String
) {
}