/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.MisbehaviourPunishmentConfig

/**
 * The configuration for punishment for improper behavior (non-validation). In the absence of the parameter, the default fine size is 101 TON
 * @param misbehaviourPunishmentConfig 
 */
data class BlockchainConfig40 (

    val misbehaviourPunishmentConfig: MisbehaviourPunishmentConfig
) {
}