/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockCurrencyCollection

/**
 * 
 * @param fromPrevBlk 
 * @param toNextBlk 
 * @param imported 
 * @param exported 
 * @param feesCollected 
 * @param burned 
 * @param feesImported 
 * @param recovered 
 * @param created 
 * @param minted 
 */
data class BlockValueFlow (

    val fromPrevBlk: BlockCurrencyCollection,
    val toNextBlk: BlockCurrencyCollection,
    val imported: BlockCurrencyCollection,
    val exported: BlockCurrencyCollection,
    val feesCollected: BlockCurrencyCollection,
    val burned: BlockCurrencyCollection? = null,
    val feesImported: BlockCurrencyCollection,
    val recovered: BlockCurrencyCollection,
    val created: BlockCurrencyCollection,
    val minted: BlockCurrencyCollection
) {
}