/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockchainConfig10
import io.swagger.client.models.BlockchainConfig11
import io.swagger.client.models.BlockchainConfig12
import io.swagger.client.models.BlockchainConfig13
import io.swagger.client.models.BlockchainConfig14
import io.swagger.client.models.BlockchainConfig15
import io.swagger.client.models.BlockchainConfig16
import io.swagger.client.models.BlockchainConfig17
import io.swagger.client.models.BlockchainConfig18
import io.swagger.client.models.BlockchainConfig20
import io.swagger.client.models.BlockchainConfig21
import io.swagger.client.models.BlockchainConfig22
import io.swagger.client.models.BlockchainConfig23
import io.swagger.client.models.BlockchainConfig24
import io.swagger.client.models.BlockchainConfig25
import io.swagger.client.models.BlockchainConfig28
import io.swagger.client.models.BlockchainConfig29
import io.swagger.client.models.BlockchainConfig31
import io.swagger.client.models.BlockchainConfig40
import io.swagger.client.models.BlockchainConfig43
import io.swagger.client.models.BlockchainConfig44
import io.swagger.client.models.BlockchainConfig5
import io.swagger.client.models.BlockchainConfig6
import io.swagger.client.models.BlockchainConfig7
import io.swagger.client.models.BlockchainConfig71
import io.swagger.client.models.BlockchainConfig79
import io.swagger.client.models.BlockchainConfig8
import io.swagger.client.models.BlockchainConfig9
import io.swagger.client.models.ValidatorsSet

/**
 * 
 * @param raw config boc in hex format
 * @param _0 config address
 * @param _1 elector address
 * @param _2 minter address
 * @param _3 The address of the transaction fee collector.
 * @param _4 dns root address
 * @param _5 
 * @param _6 
 * @param _7 
 * @param _8 
 * @param _9 
 * @param _10 
 * @param _11 
 * @param _12 
 * @param _13 
 * @param _14 
 * @param _15 
 * @param _16 
 * @param _17 
 * @param _18 
 * @param _20 
 * @param _21 
 * @param _22 
 * @param _23 
 * @param _24 
 * @param _25 
 * @param _28 
 * @param _29 
 * @param _31 
 * @param _32 
 * @param _33 
 * @param _34 
 * @param _35 
 * @param _36 
 * @param _37 
 * @param _40 
 * @param _43 
 * @param _44 
 * @param _71 
 * @param _72 
 * @param _73 
 * @param _79 
 * @param _81 
 * @param _82 
 */
data class BlockchainConfig (

    /* config boc in hex format */
    val raw: kotlin.String,
    /* config address */
    val _0: kotlin.String,
    /* elector address */
    val _1: kotlin.String,
    /* minter address */
    val _2: kotlin.String,
    /* The address of the transaction fee collector. */
    val _3: kotlin.String? = null,
    /* dns root address */
    val _4: kotlin.String,
    val _5: BlockchainConfig5? = null,
    val _6: BlockchainConfig6? = null,
    val _7: BlockchainConfig7? = null,
    val _8: BlockchainConfig8? = null,
    val _9: BlockchainConfig9? = null,
    val _10: BlockchainConfig10? = null,
    val _11: BlockchainConfig11? = null,
    val _12: BlockchainConfig12? = null,
    val _13: BlockchainConfig13? = null,
    val _14: BlockchainConfig14? = null,
    val _15: BlockchainConfig15? = null,
    val _16: BlockchainConfig16? = null,
    val _17: BlockchainConfig17? = null,
    val _18: BlockchainConfig18? = null,
    val _20: BlockchainConfig20? = null,
    val _21: BlockchainConfig21? = null,
    val _22: BlockchainConfig22? = null,
    val _23: BlockchainConfig23? = null,
    val _24: BlockchainConfig24? = null,
    val _25: BlockchainConfig25? = null,
    val _28: BlockchainConfig28? = null,
    val _29: BlockchainConfig29? = null,
    val _31: BlockchainConfig31? = null,
    val _32: ValidatorsSet? = null,
    val _33: ValidatorsSet? = null,
    val _34: ValidatorsSet? = null,
    val _35: ValidatorsSet? = null,
    val _36: ValidatorsSet? = null,
    val _37: ValidatorsSet? = null,
    val _40: BlockchainConfig40? = null,
    val _43: BlockchainConfig43? = null,
    val _44: BlockchainConfig44,
    val _71: BlockchainConfig71? = null,
    val _72: BlockchainConfig71? = null,
    val _73: BlockchainConfig71? = null,
    val _79: BlockchainConfig79? = null,
    val _81: BlockchainConfig79? = null,
    val _82: BlockchainConfig79? = null
) {
}