/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * The configuration for the Catchain protocol.
 * @param mcCatchainLifetime 
 * @param shardCatchainLifetime 
 * @param shardValidatorsLifetime 
 * @param shardValidatorsNum 
 * @param flags 
 * @param shuffleMcValidators 
 */
data class BlockchainConfig28 (

    val mcCatchainLifetime: kotlin.Long,
    val shardCatchainLifetime: kotlin.Long,
    val shardValidatorsLifetime: kotlin.Long,
    val shardValidatorsNum: kotlin.Long,
    val flags: kotlin.Int? = null,
    val shuffleMcValidators: kotlin.Boolean? = null
) {
}