/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.GasLimitPrices

/**
 * The cost of computations in the masterchain. The complexity of any computation is estimated in gas units.
 * @param gasLimitsPrices 
 */
data class BlockchainConfig20 (

    val gasLimitsPrices: GasLimitPrices
) {
}