/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * The cost of filing complaints about incorrect operation of validators.
 * @param deposit 
 * @param bitPrice 
 * @param cellPrice 
 */
data class BlockchainConfig13 (

    val deposit: kotlin.Long,
    val bitPrice: kotlin.Long,
    val cellPrice: kotlin.Long
) {
}