/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockCurrencyCollectionOther

/**
 * 
 * @param grams 
 * @param other 
 */
data class BlockCurrencyCollection (

    val grams: kotlin.Long,
    val other: kotlin.Array<BlockCurrencyCollectionOther>
) {
}