/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * The limits on the number of validators in the TON blockchain.
 * @param maxValidators 
 * @param maxMainValidators 
 * @param minValidators 
 */
data class BlockchainConfig16 (

    val maxValidators: kotlin.Int,
    val maxMainValidators: kotlin.Int,
    val minValidators: kotlin.Int
) {
}