/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockchainConfig7Currencies

/**
 * The volume of each of the additional currencies in circulation.
 * @param currencies 
 */
data class BlockchainConfig7 (

    val currencies: kotlin.Array<BlockchainConfig7Currencies>
) {
}