/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * The reward in nanoTons for block creation in the TON blockchain.
 * @param validatorsElectedFor 
 * @param electionsStartBefore 
 * @param electionsEndBefore 
 * @param stakeHeldFor 
 */
data class BlockchainConfig15 (

    val validatorsElectedFor: kotlin.Long,
    val electionsStartBefore: kotlin.Long,
    val electionsEndBefore: kotlin.Long,
    val stakeHeldFor: kotlin.Long
) {
}