/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ComputeSkipReason

/**
 * 
 * @param skipped 
 * @param skipReason 
 * @param success 
 * @param gasFees 
 * @param gasUsed 
 * @param vmSteps 
 * @param exitCode 
 * @param exitCodeDescription 
 */
data class ComputePhase (

    val skipped: kotlin.Boolean,
    val skipReason: ComputeSkipReason? = null,
    val success: kotlin.Boolean? = null,
    val gasFees: kotlin.Long? = null,
    val gasUsed: kotlin.Long? = null,
    val vmSteps: kotlin.Int? = null,
    val exitCode: kotlin.Int? = null,
    val exitCodeDescription: kotlin.String? = null
) {
}