/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * Values: NOSTATE,BADSTATE,NOGAS
 */
enum class ComputeSkipReason(val value: kotlin.String){
    NOSTATE("cskip_no_state"),// :/
    BADSTATE("cskip_bad_state"),// :/
    NOGAS("cskip_no_gas");// :/
}