/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param minTotRounds 
 * @param maxTotRounds 
 * @param minWins 
 * @param maxLosses 
 * @param minStoreSec 
 * @param maxStoreSec 
 * @param bitPrice 
 * @param cellPrice 
 */
data class ConfigProposalSetup (

    val minTotRounds: kotlin.Int,
    val maxTotRounds: kotlin.Int,
    val minWins: kotlin.Int,
    val maxLosses: kotlin.Int,
    val minStoreSec: kotlin.Long,
    val maxStoreSec: kotlin.Long,
    val bitPrice: kotlin.Long,
    val cellPrice: kotlin.Long
) {
}