/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.DecodedMessageExtInMsgDecodedWalletHighloadV2
import io.swagger.client.models.DecodedMessageExtInMsgDecodedWalletV3
import io.swagger.client.models.DecodedMessageExtInMsgDecodedWalletV4

/**
 * 
 * @param walletV3 
 * @param walletV4 
 * @param walletHighloadV2 
 */
data class DecodedMessageExtInMsgDecoded (

    val walletV3: DecodedMessageExtInMsgDecodedWalletV3? = null,
    val walletV4: DecodedMessageExtInMsgDecodedWalletV4? = null,
    val walletHighloadV2: DecodedMessageExtInMsgDecodedWalletHighloadV2? = null
) {
}