/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.WalletDNS

/**
 * 
 * @param wallet 
 * @param nextResolver 
 * @param sites 
 * @param storage tonstorage bag id
 */
data class DnsRecord (

    val wallet: WalletDNS? = null,
    val nextResolver: kotlin.String? = null,
    val sites: kotlin.Array<kotlin.String>,
    /* tonstorage bag id */
    val storage: kotlin.String? = null
) {
}