/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.NftItem

/**
 * 
 * @param name 
 * @param expiringAt date of expiring. optional. not all domain in ton has expiration date
 * @param item 
 */
data class DomainInfo (

    val name: kotlin.String,
    /* date of expiring. optional. not all domain in ton has expiration date */
    val expiringAt: kotlin.Long? = null,
    val item: NftItem? = null
) {
}