/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Action
import io.swagger.client.models.ValueFlow

/**
 * 
 * @param eventId 
 * @param timestamp 
 * @param actions 
 * @param valueFlow 
 * @param isScam scam
 * @param lt 
 * @param inProgress Event is not finished yet. Transactions still happening
 */
data class Event (

    val eventId: kotlin.String,
    val timestamp: kotlin.Long,
    val actions: kotlin.Array<Action>,
    val valueFlow: kotlin.Array<ValueFlow>,
    /* scam */
    val isScam: kotlin.Boolean,
    val lt: kotlin.Long,
    /* Event is not finished yet. Transactions still happening */
    val inProgress: kotlin.Boolean
) {
}