/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.GaslessConfigGasJettons

/**
 * 
 * @param relayAddress sending excess to this address decreases the commission of a gasless transfer
 * @param gasJettons list of jettons, any of them can be used to pay for gas
 */
data class GaslessConfig (

    /* sending excess to this address decreases the commission of a gasless transfer */
    val relayAddress: kotlin.String,
    /* list of jettons, any of them can be used to pay for gas */
    val gasJettons: kotlin.Array<GaslessConfigGasJettons>
) {
}