/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param specialGasLimit 
 * @param flatGasLimit 
 * @param flatGasPrice 
 * @param gasPrice 
 * @param gasLimit 
 * @param gasCredit 
 * @param blockGasLimit 
 * @param freezeDueLimit 
 * @param deleteDueLimit 
 */
data class GasLimitPrices (

    val specialGasLimit: kotlin.Long? = null,
    val flatGasLimit: kotlin.Long? = null,
    val flatGasPrice: kotlin.Long? = null,
    val gasPrice: kotlin.Long,
    val gasLimit: kotlin.Long,
    val gasCredit: kotlin.Long,
    val blockGasLimit: kotlin.Long,
    val freezeDueLimit: kotlin.Long,
    val deleteDueLimit: kotlin.Long
) {
}