/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.InlineResponse200Bounceable

/**
 * 
 * @param rawForm 
 * @param bounceable 
 * @param nonBounceable 
 * @param givenType 
 * @param testOnly 
 */
data class InlineResponse200 (

    val rawForm: kotlin.String,
    val bounceable: InlineResponse200Bounceable,
    val nonBounceable: InlineResponse200Bounceable,
    val givenType: kotlin.String,
    val testOnly: kotlin.Boolean
) {
}