/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.InlineResponse20029Shards

/**
 * 
 * @param extMsgQueueSizeLimit 
 * @param shards 
 */
data class InlineResponse20029 (

    val extMsgQueueSizeLimit: kotlin.Int,
    val shards: kotlin.Array<InlineResponse20029Shards>
) {
}