/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockRaw
import io.swagger.client.models.InlineResponse20026LiteServerBlockLinkForwardSignatures

/**
 * 
 * @param toKeyBlock 
 * @param from 
 * @param to 
 * @param destProof 
 * @param configProof 
 * @param signatures 
 */
data class InlineResponse20026LiteServerBlockLinkForward (

    val toKeyBlock: kotlin.Boolean,
    val from: BlockRaw,
    val to: BlockRaw,
    val destProof: kotlin.String,
    val configProof: kotlin.String,
    val signatures: InlineResponse20026LiteServerBlockLinkForwardSignatures
) {
}