/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockRaw
import io.swagger.client.models.InitStateRaw

/**
 * 
 * @param mode 
 * @param version 
 * @param capabilities 
 * @param last 
 * @param lastUtime 
 * @param now 
 * @param stateRootHash 
 * @param &#x60;init&#x60; 
 */
data class InlineResponse20015 (

    val mode: kotlin.Int,
    val version: kotlin.Int,
    val capabilities: kotlin.Long,
    val last: BlockRaw,
    val lastUtime: kotlin.Int,
    val now: kotlin.Int,
    val stateRootHash: kotlin.String,
    val `init`: InitStateRaw
) {
}