/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockRaw
import io.swagger.client.models.InlineResponse20026Steps

/**
 * 
 * @param complete 
 * @param from 
 * @param to 
 * @param steps 
 */
data class InlineResponse20026 (

    val complete: kotlin.Boolean,
    val from: BlockRaw,
    val to: BlockRaw,
    val steps: kotlin.Array<InlineResponse20026Steps>
) {
}