/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BlockRaw

/**
 * 
 * @param id 
 * @param shardblk 
 * @param shardProof 
 * @param proof 
 * @param state 
 */
data class InlineResponse20021 (

    val id: BlockRaw,
    val shardblk: BlockRaw,
    val shardProof: kotlin.String,
    val proof: kotlin.String,
    val state: kotlin.String
) {
}