/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param mode 
 * @param account 
 * @param lt 
 * @param hash 
 */
data class InlineResponse20025Ids (

    val mode: kotlin.Int,
    val account: kotlin.String? = null,
    val lt: kotlin.Long? = null,
    val hash: kotlin.String? = null
) {
}