/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.JettonVerificationType

/**
 * 
 * @param address 
 * @param name 
 * @param symbol 
 * @param decimals 
 * @param image 
 * @param verification 
 */
data class JettonPreview (

    val address: kotlin.String,
    val name: kotlin.String,
    val symbol: kotlin.String,
    val decimals: kotlin.Int,
    val image: kotlin.String,
    val verification: JettonVerificationType
) {
}