/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.JettonBridgePrices
import io.swagger.client.models.Oracle

/**
 * 
 * @param bridgeAddress 
 * @param oraclesAddress 
 * @param stateFlags 
 * @param burnBridgeFee 
 * @param oracles 
 * @param externalChainAddress 
 * @param prices 
 */
data class JettonBridgeParams (

    val bridgeAddress: kotlin.String,
    val oraclesAddress: kotlin.String,
    val stateFlags: kotlin.Int,
    val burnBridgeFee: kotlin.Long? = null,
    val oracles: kotlin.Array<Oracle>,
    val externalChainAddress: kotlin.String? = null,
    val prices: JettonBridgePrices? = null
) {
}