/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param name 
 * @param symbol 
 * @param decimals 
 * @param image 
 * @param description 
 * @param social 
 * @param websites 
 * @param catalogs 
 */
data class JettonMetadata (

    val address: kotlin.String,
    val name: kotlin.String,
    val symbol: kotlin.String,
    val decimals: kotlin.String,
    val image: kotlin.String? = null,
    val description: kotlin.String? = null,
    val social: kotlin.Array<kotlin.String>? = null,
    val websites: kotlin.Array<kotlin.String>? = null,
    val catalogs: kotlin.Array<kotlin.String>? = null
) {
}