/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.JettonBalanceLock
import io.swagger.client.models.JettonPreview
import io.swagger.client.models.TokenRates

/**
 * 
 * @param balance 
 * @param price 
 * @param walletAddress 
 * @param jetton 
 * @param extensions 
 * @param lock 
 */
data class JettonBalance (

    val balance: kotlin.String,
    val price: TokenRates? = null,
    val walletAddress: AccountAddress,
    val jetton: JettonPreview,
    val extensions: kotlin.Array<kotlin.String>? = null,
    val lock: JettonBalanceLock? = null
) {
}