/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.JettonMetadata
import io.swagger.client.models.JettonVerificationType

/**
 * 
 * @param mintable 
 * @param totalSupply 
 * @param admin 
 * @param metadata 
 * @param verification 
 * @param holdersCount 
 */
data class JettonInfo (

    val mintable: kotlin.Boolean,
    val totalSupply: kotlin.String,
    val admin: AccountAddress? = null,
    val metadata: JettonMetadata,
    val verification: JettonVerificationType,
    val holdersCount: kotlin.Int
) {
}