/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.EncryptedComment
import io.swagger.client.models.JettonPreview
import io.swagger.client.models.Refund

/**
 * 
 * @param sender 
 * @param recipient 
 * @param sendersWallet 
 * @param recipientsWallet 
 * @param amount amount in quanta of tokens
 * @param comment 
 * @param encryptedComment 
 * @param refund 
 * @param jetton 
 */
data class JettonTransferAction (

    val sender: AccountAddress? = null,
    val recipient: AccountAddress? = null,
    val sendersWallet: kotlin.String,
    val recipientsWallet: kotlin.String,
    /* amount in quanta of tokens */
    val amount: kotlin.String,
    val comment: kotlin.String? = null,
    val encryptedComment: EncryptedComment? = null,
    val refund: Refund? = null,
    val jetton: JettonPreview
) {
}