/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param bridgeBurnFee 
 * @param bridgeMintFee 
 * @param walletMinTonsForStorage 
 * @param walletGasConsumption 
 * @param minterMinTonsForStorage 
 * @param discoverGasConsumption 
 */
data class JettonBridgePrices (

    val bridgeBurnFee: kotlin.Long,
    val bridgeMintFee: kotlin.Long,
    val walletMinTonsForStorage: kotlin.Long,
    val walletGasConsumption: kotlin.Long,
    val minterMinTonsForStorage: kotlin.Long,
    val discoverGasConsumption: kotlin.Long
) {
}