/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param market 
 * @param usdPrice 
 * @param lastDateUpdate 
 */
data class MarketTonRates (

    val market: kotlin.String,
    val usdPrice: java.math.BigDecimal,
    val lastDateUpdate: kotlin.Long
) {
}