/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountEvent
import io.swagger.client.models.Risk
import io.swagger.client.models.Trace

/**
 * 
 * @param trace 
 * @param risk 
 * @param event 
 */
data class MessageConsequences (

    val trace: Trace,
    val risk: Risk,
    val event: AccountEvent
) {
}