/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.StateInit

/**
 * 
 * @param msgType 
 * @param createdLt 
 * @param ihrDisabled 
 * @param bounce 
 * @param bounced 
 * @param value 
 * @param fwdFee 
 * @param ihrFee 
 * @param destination 
 * @param source 
 * @param importFee 
 * @param createdAt 
 * @param opCode 
 * @param &#x60;init&#x60; 
 * @param hash 
 * @param rawBody hex-encoded BoC with raw message body
 * @param decodedOpName 
 * @param decodedBody 
 */
data class Message (

    val msgType: MsgType,
    val createdLt: kotlin.Long,
    val ihrDisabled: kotlin.Boolean,
    val bounce: kotlin.Boolean,
    val bounced: kotlin.Boolean,
    val value: kotlin.Long,
    val fwdFee: kotlin.Long,
    val ihrFee: kotlin.Long,
    val destination: AccountAddress? = null,
    val source: AccountAddress? = null,
    val importFee: kotlin.Long,
    val createdAt: kotlin.Long,
    val opCode: kotlin.String? = null,
    val `init`: StateInit? = null,
    val hash: kotlin.String,
    /* hex-encoded BoC with raw message body */
    val rawBody: kotlin.String? = null,
    val decodedOpName: kotlin.String? = null,
    val decodedBody: kotlin.Any? = null
) {
    /**
    * 
    * Values: INTMSG,EXTINMSG,EXTOUTMSG
    */
    enum class MsgType(val value: kotlin.String){
        INTMSG("int_msg"),
        EXTINMSG("ext_in_msg"),
        EXTOUTMSG("ext_out_msg");
    }
}