/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.TvmStackRecord

/**
 * 
 * @param success 
 * @param exitCode tvm exit code
 * @param stack 
 * @param decoded 
 */
data class MethodExecutionResult (

    val success: kotlin.Boolean,
    /* tvm exit code */
    val exitCode: kotlin.Int,
    val stack: kotlin.Array<TvmStackRecord>,
    val decoded: kotlin.Any? = null
) {
}