/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param defaultFlatFine 
 * @param defaultProportionalFine 
 * @param severityFlatMult 
 * @param severityProportionalMult 
 * @param unpunishableInterval 
 * @param longInterval 
 * @param longFlatMult 
 * @param longProportionalMult 
 * @param mediumInterval 
 * @param mediumFlatMult 
 * @param mediumProportionalMult 
 */
data class MisbehaviourPunishmentConfig (

    val defaultFlatFine: kotlin.Long,
    val defaultProportionalFine: kotlin.Long,
    val severityFlatMult: kotlin.Int,
    val severityProportionalMult: kotlin.Int,
    val unpunishableInterval: kotlin.Int,
    val longInterval: kotlin.Int,
    val longFlatMult: kotlin.Int,
    val longProportionalMult: kotlin.Int,
    val mediumInterval: kotlin.Int,
    val mediumFlatMult: kotlin.Int,
    val mediumProportionalMult: kotlin.Int
) {
}