/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param lumpPrice 
 * @param bitPrice 
 * @param cellPrice 
 * @param ihrPriceFactor 
 * @param firstFrac 
 * @param nextFrac 
 */
data class MsgForwardPrices (

    val lumpPrice: kotlin.Long,
    val bitPrice: kotlin.Long,
    val cellPrice: kotlin.Long,
    val ihrPriceFactor: kotlin.Long,
    val firstFrac: kotlin.Long,
    val nextFrac: kotlin.Long
) {
}