/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.MultisigOrder

/**
 * 
 * @param address 
 * @param seqno 
 * @param threshold 
 * @param signers 
 * @param proposers 
 * @param orders 
 */
data class Multisig (

    val address: kotlin.String,
    val seqno: kotlin.Long,
    val threshold: kotlin.Int,
    val signers: kotlin.Array<kotlin.String>,
    val proposers: kotlin.Array<kotlin.String>,
    val orders: kotlin.Array<MultisigOrder>
) {
}