/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Risk

/**
 * 
 * @param address 
 * @param orderSeqno 
 * @param threshold 
 * @param sentForExecution 
 * @param signers 
 * @param approvalsNum 
 * @param expirationDate 
 * @param risk 
 */
data class MultisigOrder (

    val address: kotlin.String,
    val orderSeqno: kotlin.Long,
    val threshold: kotlin.Int,
    val sentForExecution: kotlin.Boolean,
    val signers: kotlin.Array<kotlin.String>,
    val approvalsNum: kotlin.Int,
    val expirationDate: kotlin.Long,
    val risk: Risk
) {
}