/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.ImagePreview
import io.swagger.client.models.NftApprovedBy
import io.swagger.client.models.NftItemCollection
import io.swagger.client.models.Sale
import io.swagger.client.models.TrustType

/**
 * 
 * @param address 
 * @param index 
 * @param owner 
 * @param collection 
 * @param verified 
 * @param metadata 
 * @param sale 
 * @param previews 
 * @param dns 
 * @param approvedBy 
 * @param includeCnft 
 * @param trust 
 */
data class NftItem (

    val address: kotlin.String,
    val index: kotlin.Long,
    val owner: AccountAddress? = null,
    val collection: NftItemCollection? = null,
    val verified: kotlin.Boolean,
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,
    val sale: Sale? = null,
    val previews: kotlin.Array<ImagePreview>? = null,
    val dns: kotlin.String? = null,
    val approvedBy: NftApprovedBy,
    val includeCnft: kotlin.Boolean? = null,
    val trust: TrustType
) {
}