/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.NftItem
import io.swagger.client.models.Price

/**
 * 
 * @param auctionType 
 * @param amount 
 * @param nft 
 * @param seller 
 * @param buyer 
 */
data class NftPurchaseAction (

    val auctionType: AuctionType,
    val amount: Price,
    val nft: NftItem,
    val seller: AccountAddress,
    val buyer: AccountAddress
) {
    /**
    * 
    * Values: DNSPERIODTON,DNSPERIODTG,NUMBERPERIODTG,GETGEMS
    */
    enum class AuctionType(val value: kotlin.String){
        DNSPERIODTON("DNS.ton"),
        DNSPERIODTG("DNS.tg"),
        NUMBERPERIODTG("NUMBER.tg"),
        GETGEMS("getgems");
    }
}