/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Oracle

/**
 * 
 * @param bridgeAddr 
 * @param oracleMultisigAddress 
 * @param externalChainAddress 
 * @param oracles 
 */
data class OracleBridgeParams (

    val bridgeAddr: kotlin.String,
    val oracleMultisigAddress: kotlin.String,
    val externalChainAddress: kotlin.String,
    val oracles: kotlin.Array<Oracle>
) {
}