/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.PoolImplementationType

/**
 * 
 * @param address 
 * @param name 
 * @param totalAmount 
 * @param implementation 
 * @param apy APY in percent
 * @param minStake 
 * @param cycleStart current nomination cycle beginning timestamp
 * @param cycleEnd current nomination cycle ending timestamp
 * @param verified this pool has verified source code or managed by trusted company
 * @param currentNominators current number of nominators
 * @param maxNominators maximum number of nominators
 * @param liquidJettonMaster for liquid staking master account of jetton
 * @param nominatorsStake total stake of all nominators
 * @param validatorStake stake of validator
 * @param cycleLength 
 */
data class PoolInfo (

    val address: kotlin.String,
    val name: kotlin.String,
    val totalAmount: kotlin.Long,
    val implementation: PoolImplementationType,
    /* APY in percent */
    val apy: java.math.BigDecimal,
    val minStake: kotlin.Long,
    /* current nomination cycle beginning timestamp */
    val cycleStart: kotlin.Long,
    /* current nomination cycle ending timestamp */
    val cycleEnd: kotlin.Long,
    /* this pool has verified source code or managed by trusted company */
    val verified: kotlin.Boolean,
    /* current number of nominators */
    val currentNominators: kotlin.Int,
    /* maximum number of nominators */
    val maxNominators: kotlin.Int,
    /* for liquid staking master account of jetton */
    val liquidJettonMaster: kotlin.String? = null,
    /* total stake of all nominators */
    val nominatorsStake: kotlin.Long,
    /* stake of validator */
    val validatorStake: kotlin.Long,
    val cycleLength: kotlin.Long? = null
) {
}