/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param workchainId 
 * @param shard 
 * @param seqno 
 * @param masterRef 
 * @param txQuantity 
 * @param utime 
 * @param shardsBlocks 
 * @param parent 
 */
data class ReducedBlock (

    val workchainId: kotlin.Int,
    val shard: kotlin.String,
    val seqno: kotlin.Int,
    val masterRef: kotlin.String? = null,
    val txQuantity: kotlin.Int,
    val utime: kotlin.Long,
    val shardsBlocks: kotlin.Array<kotlin.String>,
    val parent: kotlin.Array<kotlin.String>
) {
}