/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param type 
 * @param origin 
 */
data class Refund (

    val type: Type,
    val origin: kotlin.String
) {
    /**
    * 
    * Values: DNSPERIODTON,DNSPERIODTG,GETGEMS
    */
    enum class Type(val value: kotlin.String){
        DNSPERIODTON("DNS.ton"),
        DNSPERIODTG("DNS.tg"),
        GETGEMS("GetGems");
    }
}