/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.JettonQuantity
import io.swagger.client.models.NftItem

/**
 * Risk specifies assets that could be lost if a message would be sent to a malicious smart contract. It makes sense to understand the risk BEFORE sending a message to the blockchain.
 * @param transferAllRemainingBalance transfer all the remaining balance of the wallet.
 * @param ton 
 * @param jettons 
 * @param nfts 
 */
data class Risk (

    /* transfer all the remaining balance of the wallet. */
    val transferAllRemainingBalance: kotlin.Boolean,
    val ton: kotlin.Long,
    val jettons: kotlin.Array<JettonQuantity>,
    val nfts: kotlin.Array<NftItem>
) {
}