/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param amount Number of nanocoins to send. Decimal string.
 * @param payload Raw one-cell BoC encoded in hex.
 * @param stateInit Raw once-cell BoC encoded in hex.
 */
data class SignRawMessage (

    val address: kotlin.String,
    /* Number of nanocoins to send. Decimal string. */
    val amount: kotlin.String,
    /* Raw one-cell BoC encoded in hex. */
    val payload: kotlin.String? = null,
    /* Raw once-cell BoC encoded in hex. */
    val stateInit: kotlin.String? = null
) {
}