/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.SignRawMessage

/**
 * 
 * @param relayAddress 
 * @param commission Commission for the transaction. In nanocoins.
 * @param from 
 * @param validUntil 
 * @param messages 
 */
data class SignRawParams (

    val relayAddress: kotlin.String,
    /* Commission for the transaction. In nanocoins. */
    val commission: kotlin.String,
    val from: kotlin.String,
    val validUntil: kotlin.Long,
    val messages: kotlin.Array<SignRawMessage>
) {
}