/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param maxMsgBits 
 * @param maxMsgCells 
 * @param maxLibraryCells 
 * @param maxVmDataDepth 
 * @param maxExtMsgSize 
 * @param maxExtMsgDepth 
 * @param maxAccStateCells 
 * @param maxAccStateBits 
 */
data class SizeLimitsConfig (

    val maxMsgBits: kotlin.Long,
    val maxMsgCells: kotlin.Long,
    val maxLibraryCells: kotlin.Long,
    val maxVmDataDepth: kotlin.Int,
    val maxExtMsgSize: kotlin.Long,
    val maxExtMsgDepth: kotlin.Int,
    val maxAccStateCells: kotlin.Long? = null,
    val maxAccStateBits: kotlin.Long? = null
) {
}