/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.Refund

/**
 * 
 * @param executor 
 * @param contract 
 * @param tonAttached amount in nanotons
 * @param operation 
 * @param payload 
 * @param refund 
 */
data class SmartContractAction (

    val executor: AccountAddress,
    val contract: AccountAddress,
    /* amount in nanotons */
    val tonAttached: kotlin.Long,
    val operation: kotlin.String,
    val payload: kotlin.String? = null,
    val refund: Refund? = null
) {
}