/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param acceptNewContracts 
 * @param ratePerMbDay 
 * @param maxSpan 
 * @param minimalFileSize 
 * @param maximalFileSize 
 */
data class StorageProvider (

    val address: kotlin.String,
    val acceptNewContracts: kotlin.Boolean,
    val ratePerMbDay: kotlin.Long,
    val maxSpan: kotlin.Long,
    val minimalFileSize: kotlin.Long,
    val maximalFileSize: kotlin.Long
) {
}