/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress

/**
 * 
 * @param subscriber 
 * @param subscription 
 * @param beneficiary 
 * @param amount 
 * @param initial 
 */
data class SubscriptionAction (

    val subscriber: AccountAddress,
    val subscription: kotlin.String,
    val beneficiary: AccountAddress,
    val amount: kotlin.Long,
    val initial: kotlin.Boolean
) {
}