/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param walletAddress 
 * @param beneficiaryAddress 
 * @param amount 
 * @param period 
 * @param startTime 
 * @param timeout 
 * @param lastPaymentTime 
 * @param lastRequestTime 
 * @param subscriptionId 
 * @param failedAttempts 
 */
data class Subscription (

    val address: kotlin.String,
    val walletAddress: kotlin.String,
    val beneficiaryAddress: kotlin.String,
    val amount: kotlin.Long,
    val period: kotlin.Long,
    val startTime: kotlin.Long,
    val timeout: kotlin.Long,
    val lastPaymentTime: kotlin.Long,
    val lastRequestTime: kotlin.Long,
    val subscriptionId: kotlin.Long,
    val failedAttempts: kotlin.Int
) {
}