/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param prices 
 * @param diff24h 
 * @param diff7d 
 * @param diff30d 
 */
data class TokenRates (

    val prices: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null,
    val diff24h: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val diff7d: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val diff30d: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
) {
}