/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Trace
import io.swagger.client.models.Transaction

/**
 * 
 * @param transaction 
 * @param interfaces 
 * @param children 
 * @param emulated 
 */
data class Trace (

    val transaction: Transaction,
    val interfaces: kotlin.Array<kotlin.String>,
    val children: kotlin.Array<Trace>? = null,
    val emulated: kotlin.Boolean? = null
) {
}