/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress
import io.swagger.client.models.AccountStatus
import io.swagger.client.models.ActionPhase
import io.swagger.client.models.BouncePhaseType
import io.swagger.client.models.ComputePhase
import io.swagger.client.models.CreditPhase
import io.swagger.client.models.Message
import io.swagger.client.models.StoragePhase
import io.swagger.client.models.TransactionType

/**
 * 
 * @param hash 
 * @param lt 
 * @param account 
 * @param success 
 * @param utime 
 * @param origStatus 
 * @param endStatus 
 * @param totalFees 
 * @param endBalance 
 * @param transactionType 
 * @param stateUpdateOld 
 * @param stateUpdateNew 
 * @param inMsg 
 * @param outMsgs 
 * @param block 
 * @param prevTransHash 
 * @param prevTransLt 
 * @param computePhase 
 * @param storagePhase 
 * @param creditPhase 
 * @param actionPhase 
 * @param bouncePhase 
 * @param aborted 
 * @param destroyed 
 * @param raw hex encoded boc with raw transaction
 */
data class Transaction (

    val hash: kotlin.String,
    val lt: kotlin.Long,
    val account: AccountAddress,
    val success: kotlin.Boolean,
    val utime: kotlin.Long,
    val origStatus: AccountStatus,
    val endStatus: AccountStatus,
    val totalFees: kotlin.Long,
    val endBalance: kotlin.Long,
    val transactionType: TransactionType,
    val stateUpdateOld: kotlin.String,
    val stateUpdateNew: kotlin.String,
    val inMsg: Message? = null,
    val outMsgs: kotlin.Array<Message>,
    val block: kotlin.String,
    val prevTransHash: kotlin.String? = null,
    val prevTransLt: kotlin.Long? = null,
    val computePhase: ComputePhase? = null,
    val storagePhase: StoragePhase? = null,
    val creditPhase: CreditPhase? = null,
    val actionPhase: ActionPhase? = null,
    val bouncePhase: BouncePhaseType? = null,
    val aborted: kotlin.Boolean,
    val destroyed: kotlin.Boolean,
    /* hex encoded boc with raw transaction */
    val raw: kotlin.String
) {
}