/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.TvmStackRecord

/**
 * 
 * @param type 
 * @param cell 
 * @param slice 
 * @param num 
 * @param tuple 
 */
data class TvmStackRecord (

    val type: Type,
    val cell: kotlin.String? = null,
    val slice: kotlin.String? = null,
    val num: kotlin.String? = null,
    val tuple: kotlin.Array<TvmStackRecord>? = null
) {
    /**
    * 
    * Values: CELL,NUM,NAN,NULL,TUPLE
    */
    enum class Type(val value: kotlin.String){
        CELL("cell"),
        NUM("num"),
        NAN("nan"),
        NULL("null"),
        TUPLE("tuple");
    }
}