/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param adnlAddress 
 * @param stake 
 * @param maxFactor 
 */
data class Validator (

    val address: kotlin.String,
    val adnlAddress: kotlin.String,
    val stake: kotlin.Long,
    val maxFactor: kotlin.Long
) {
}