/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ValidatorsSetList

/**
 * 
 * @param utimeSince 
 * @param utimeUntil 
 * @param total 
 * @param main 
 * @param totalWeight 
 * @param list 
 */
data class ValidatorsSet (

    val utimeSince: kotlin.Int,
    val utimeUntil: kotlin.Int,
    val total: kotlin.Int,
    val main: kotlin.Int,
    val totalWeight: kotlin.String? = null,
    val list: kotlin.Array<ValidatorsSetList>
) {
}