/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AccountAddress

/**
 * 
 * @param address 
 * @param account 
 * @param isWallet 
 * @param hasMethodPubkey 
 * @param hasMethodSeqno 
 * @param names 
 */
data class WalletDNS (

    val address: kotlin.String,
    val account: AccountAddress,
    val isWallet: kotlin.Boolean,
    val hasMethodPubkey: kotlin.Boolean,
    val hasMethodSeqno: kotlin.Boolean,
    val names: kotlin.Array<kotlin.String>
) {
}