/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param workchain 
 * @param enabledSince 
 * @param actualMinSplit 
 * @param minSplit 
 * @param maxSplit 
 * @param basic 
 * @param active 
 * @param acceptMsgs 
 * @param flags 
 * @param zerostateRootHash 
 * @param zerostateFileHash 
 * @param version 
 */
data class WorkchainDescr (

    val workchain: kotlin.Int,
    val enabledSince: kotlin.Long,
    val actualMinSplit: kotlin.Int,
    val minSplit: kotlin.Int,
    val maxSplit: kotlin.Int,
    val basic: kotlin.Int,
    val active: kotlin.Boolean,
    val acceptMsgs: kotlin.Boolean,
    val flags: kotlin.Int,
    val zerostateRootHash: kotlin.String,
    val zerostateFileHash: kotlin.String,
    val version: kotlin.Long
) {
}